cd

diff --git a/.github/actions/setup-node-and-install/action.yml b/.github/actions/setup-node-and-install/action.yml
--- a/.github/actions/setup-node-and-install/action.yml
+++ b/.github/actions/setup-node-and-install/action.yml
@@ -8,8 +8,13 @@ runs:
       uses: actions/setup-node@v6
       with:
         node-version-file: '.nvmrc'
-        cache: npm
+        cache: 'none'
 
     - name: Install dependencies
       run: npm ci
       shell: bash
+
+    - name: Check Angular CLI
+      run: |
+        echo "Checking for NG in node_modules:"
+        ls -la node_modules/.bin | grep ng || echo "NG not found"
